{% set version = "2.44" %}

package:
  name: xkeyboard-config
  version: {{ version }}

source:
  url: http://www.x.org/releases/individual/data/xkeyboard-config/xkeyboard-config-{{ version }}.tar.xz
  sha256: 54d2c33eeebb031d48fa590c543e54c9bcbd0f00386ebc6489b2f47a0da4342a

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    # Perl is required implicitly:
    # $BUILD_PREFIX/bin/meson --internal exe --capture rules/base.lst -- $SRC_DIR/rules/xml2lst.pl rules/base.xml
    # /usr/bin/env: perl: No such file or directory
    # see https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/xkeyboard-config-2.44/rules/meson.build?ref_type=tags#L165
    - perl
    - meson
    - make
  host:
    - xorg-xorgproto
    - xorg-libx11

test:
  commands:
    - test -f "${PREFIX}/share/X11/xkb/geometry/hp"

about:
  home: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The non-arch keyboard configuration database for X Windows
  description: |
    The goal is to provide the consistent, well-structured, frequently
    released open source of X keyboard configuration data for X Window
    System implementations (free, open source and commercial).
    The project is targeted to XKB-based systems.
  doc_url: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
  dev_url: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
