{% set name = "xkeyboard-config" %}
{% set version = "2.48" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/data/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: b77041324f0109f77161ee43743fe04baa485866af8460d31e476ad3f7648fd5

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    # Perl is required implicitly:
    # $BUILD_PREFIX/bin/meson --internal exe --capture rules/base.lst -- $SRC_DIR/rules/xml2lst.pl rules/base.xml
    # /usr/bin/env: perl: No such file or directory
    # see https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/xkeyboard-config-2.44/rules/meson.build?ref_type=tags#L165
    - perl
    - meson
    - ninja-base
    - make
    - gawk  # [osx]
  host:
    - xorg-xorgproto {{ xorg_xorgproto }}
    - xorg-libx11 {{ xorg_libx11 }}

test:
  commands:
    - test -f "${PREFIX}/share/X11/xkb/geometry/hp"

about:
  home: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The non-arch keyboard configuration database for X Windows
  description: |
    The goal is to provide the consistent, well-structured, frequently
    released open source of X keyboard configuration data for X Window
    System implementations (free, open source and commercial).
    The project is targeted to XKB-based systems.
  doc_url: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
  dev_url: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config

extra:
  recipe-maintainers:
    - scopatz
    - hmaarrfk
  skip-lints:
    # meson is a native build tool, not a host dependency.
    - python_build_tools_in_host
